<?php

/**
 * @file
 *   Plural formula configurator module.
 *
 *   Drupal itself does not let you edit plural formulas for languages because
 *   of the complexity involved. This is an "advanced" user module letting you
 *   edit the plural formulas, providing sensible defaults.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function l10n_pconfig_form_language_admin_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('l10n_pconfig.language_form')->form($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function l10n_pconfig_form_language_admin_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('l10n_pconfig.language_form')->form($form, $form_state);
}
